
language: python
python:
  - '3.7'
  - '3.9'
branches:
  only:
    - main
    - dev
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/whattodo
install:
  - pip install pipenv
  - pipenv install --system --dev
script:
  - tox -e py
after_success:
  - bash <(curl -s https://codecov.io/bash)