[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["isort", "test"]

[tool.black]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88

[tool.pylint]
disable = C0330, C0326
max-line-length = 88
