[tool.pipenv]
name = "whattodo"
version = "0.0.0"
description = ""
authors = ["Alexandre Xavier <ale.bxsantos@gmail.com.br>"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "smoke: mark tests as smoke, showing the health of the project (run using '-m \"smoke\"')",
]

[tool.black]
include_trailing_comma = true
ensure_newline_before_comments = true
line_length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
)
'''

[tool.mypy]
ignore_missing_imports = true
